import test from 'node:test';
import assert from 'node:assert/strict';
import { freshState,validateSave,collectShard,reward,restoreBeacon,buyUpgrade,usePotion,respawn,maxHealth,levelOf,swordDamage,WORLD_BOUNDARY } from '../src/state.js';
const orders=[['grove','tide','crown'],['grove','crown','tide'],['tide','grove','crown'],['tide','crown','grove'],['crown','grove','tide'],['crown','tide','grove']];
test('all six beacon orders complete and each beacon rewards only once',()=>{
  for(const order of orders){const s=freshState();for(const id of order){assert.equal(restoreBeacon(s,id,true),false);assert.equal(restoreBeacon(s,id,false),true);const before=structuredClone(s);assert.equal(restoreBeacon(s,id,false),false);assert.deepEqual(s,before);}assert.equal(s.beacons.length,3);assert.equal(s.shards,45);assert.equal(s.xp,225);assert.equal(s.hp,maxHealth(s));assert.equal(s.potions,3);}
});
test('collectibles cannot duplicate rewards after saving and loading',()=>{const s=freshState();assert.ok(collectShard(s,4));const loaded=validateSave(JSON.parse(JSON.stringify(s)));assert.equal(collectShard(loaded,4),false);assert.equal(loaded.shards,1);});
test('upgrades require funds, have a cap, and apply the promised stats',()=>{const s=freshState();assert.equal(buyUpgrade(s,'sword'),false);s.shards=200;for(let i=0;i<3;i++)assert.ok(buyUpgrade(s,'sword'));assert.equal(swordDamage(s),55);assert.equal(s.shards,110);assert.equal(buyUpgrade(s,'sword'),false);assert.equal(buyUpgrade(s,'__proto__'),false);s.hp=50;assert.ok(buyUpgrade(s,'vitality'));assert.equal(maxHealth(s),125);assert.equal(s.hp,75);});
test('level-up heals and increases health and sword damage',()=>{const s=freshState();s.hp=10;assert.ok(reward(s,120,10));assert.equal(levelOf(s),2);assert.equal(s.hp,115);assert.equal(swordDamage(s),29);});
test('healing clamps at max health and never wastes a full-health flask',()=>{const s=freshState();assert.equal(usePotion(s),false);assert.equal(s.potions,3);s.hp=80;assert.ok(usePotion(s));assert.equal(s.hp,100);assert.equal(s.potions,2);s.potions=0;s.hp=20;assert.equal(usePotion(s),false);});
test('death and reload recover safely at camp without losing progression',()=>{const s=freshState();s.hp=0;s.x=50;s.z=-38;s.beacons=['tide'];s.defeated=['tide-keeper'];s.shards=32;s.potions=0;const loaded=validateSave(s);assert.equal(loaded.x,0);assert.equal(loaded.z,44);assert.equal(loaded.hp,maxHealth(loaded));assert.equal(loaded.potions,3);assert.deepEqual(loaded.beacons,['tide']);assert.deepEqual(loaded.defeated,['tide-keeper']);assert.equal(loaded.shards,32);});
test('all reachable world-edge positions survive save round-trips',()=>{for(const a of [0,1,2,3]){const s=freshState();s.x=Math.sin(a)*WORLD_BOUNDARY;s.z=Math.cos(a)*WORLD_BOUNDARY;const loaded=validateSave(s);assert.equal(loaded.x,s.x);assert.equal(loaded.z,s.z);}});
test('malformed saves cannot inject invalid positions or upgrade ranks',()=>{assert.equal(validateSave(null),null);assert.equal(validateSave({version:5}),null);const s=validateSave({version:1,x:Infinity,z:NaN,hp:-20,shards:-5,sword:99,beacons:['grove','invalid','grove'],collected:'oops',won:true});assert.equal(s.x,0);assert.equal(s.shards,0);assert.equal(s.sword,3);assert.deepEqual(s.beacons,['grove']);assert.deepEqual(s.collected,[]);assert.equal(s.won,false);});
test('victory survives a complete save, and recovery preserves the ending',()=>{const s=freshState();s.beacons=['grove','tide','crown'];s.defeated=['warden'];s.won=true;const loaded=validateSave(s);assert.equal(loaded.won,true);respawn(loaded);assert.equal(loaded.won,true);});
