import * as THREE from '../vendor/three.module.js';
import {createPost} from './post.js';
import {createWorld,createCharacter,createEnemy,heightAt,BEACONS,CAMP,GATE} from './world.js';
import {WORLD_BOUNDARY,SAVE_KEY,freshState,validateSave,levelOf,maxHealth,swordDamage,upgradeCost,collectShard,reward,restoreBeacon,buyUpgrade,usePotion,respawn} from './state.js';
const $=id=>document.getElementById(id), show=(id,yes=true)=>$(id).classList.toggle('hidden',!yes);
let saved=null, storageAvailable=true;
try{const raw=localStorage.getItem(SAVE_KEY);try{saved=validateSave(JSON.parse(raw));}catch{saved=null;}}catch{storageAvailable=false;}
let state=saved||freshState();

function init(){
  const scene=new THREE.Scene();scene.fog=new THREE.FogExp2(0xb8cdbb,.0038);
  const renderer=new THREE.WebGLRenderer({canvas:$('world'),antialias:true,powerPreference:'high-performance'});
  renderer.setPixelRatio(Math.min(devicePixelRatio,1.65));renderer.setSize(innerWidth,innerHeight);renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.05;
  const post=createPost(renderer);
  const camera=new THREE.PerspectiveCamera(51,innerWidth/innerHeight,.1,1100);
  scene.add(new THREE.HemisphereLight(0xe1f1d6,0x536f67,1.25));
  const sun=new THREE.DirectionalLight(0xffe1aa,2.6);sun.position.set(-35,75,25);sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);Object.assign(sun.shadow.camera,{left:-78,right:78,top:78,bottom:-78,near:1,far:200});sun.shadow.bias=-.00035;sun.shadow.normalBias=.045;scene.add(sun);scene.add(sun.target);
  const world=createWorld(scene),player=createCharacter();scene.add(player);
  const keys=new Set(), enemies=[],particles=[],floaters=[];let playing=false,modalOpen=false,modalKind='',last=performance.now(),time=0,saveTime=0,mapTime=0,yaw=0,pitch=.26,zoom=14,stamina=100,attackTimer=0,attackCooldown=0,dodgeTimer=0,dodgeCooldown=0,invincible=0,vertical=0,jumpY=0,movePhase=0,shake=0,nearby=null,toastTimeout,discoveryTimeout,activeRegion='',lastFocus=null,bossSpawned=false,drag=null,quality='high',waypoint=null;
  const moveVector=new THREE.Vector3(),cameraTarget=new THREE.Vector3(),cameraPosition=new THREE.Vector3(),dodgeVector=new THREE.Vector3(0,0,-1);
  const trail=new THREE.Mesh(new THREE.RingGeometry(1.3,2.8,32,1,0,Math.PI*1.35),new THREE.MeshBasicMaterial({color:0xffe5ac,transparent:true,opacity:0,side:THREE.DoubleSide,depthWrite:false}));trail.rotation.x=-Math.PI/2;scene.add(trail);
  const audio=new Soundscape();
  function spawnEnemy(id,x,z,tier,beacon=null){const e=createEnemy(scene,x,z,tier);e.id=id;e.beacon=beacon;if(state.defeated.includes(id)){e.dead=true;e.object.visible=false;}enemies.push(e);return e;}
  BEACONS.forEach((b,i)=>{spawnEnemy(`${b.id}-keeper`,b.x+4,b.z+7,2,b.id);spawnEnemy(`${b.id}-sentinel`,b.x-5,b.z+8,1,b.id);spawnEnemy(`${b.id}-watcher`,b.x+6,b.z-5,1,b.id);});
  [[-22,15],[-34,-1],[23,-6],[38,-20],[-7,-48],[8,-61],[-78,47],[75,7]].forEach(([x,z],i)=>spawnEnemy(`roamer-${i}`,x,z,1));
  function surfaceAt(x,z){let y=heightAt(x,z);if(Math.hypot(x,z+18)<12.4)y=Math.max(y,heightAt(0,-18)+1.15);for(const b of BEACONS)if(Math.hypot(x-b.x,z-b.z)<5.6)y=Math.max(y,heightAt(b.x,b.z)+.7);if(Math.abs(x-19)<2.65&&z>16.2&&z<37){const t=THREE.MathUtils.clamp((z-17)/19.2,0,1);y=Math.max(y,heightAt(19,17)+1.04+Math.sin(t*Math.PI)*1.3);}return Math.max(y,1.7);}
  function resetPosition(){player.position.set(state.x,surfaceAt(state.x,state.z),state.z);player.rotation.y=Math.PI;camera.position.set(state.x,state.hp?player.position.y+8:12,state.z+13);jumpY=0;vertical=0;}
  function applyWorldState(){world.pickups.forEach(p=>p.object.visible=!state.collected.includes(p.id));for(const b of world.beaconObjects){const lit=state.beacons.includes(b.id);b.crystal.material.emissiveIntensity=lit?2.1:.45;b.beam.material.opacity=lit?.2:.045;b.light.intensity=lit?35:0;}if(state.beacons.length===3&&!bossSpawned){bossSpawned=true;spawnEnemy('warden',0,-21,3);}world.gateCore.material.emissiveIntensity=state.won?3:1.4;}
  resetPosition();applyWorldState();updateHUD();
  $('start').disabled=false;$('start').querySelector('span').textContent=saved?'Continue your journey':'Begin your journey';show('new-game',!!saved);
  $('start').onclick=()=>start();$('new-game').onclick=()=>{openModal('new',`<div class="modal-eyebrow">A FRESH BEGINNING</div><h2 id="modal-title">Begin again?</h2><p>This replaces the journey saved in this browser. Your current beacon, upgrade, and exploration progress will be lost.</p><button class="primary" id="confirm-new">Begin a new journey <b>↗</b></button><button class="secondary" id="cancel-new">Keep my journey</button>`);$('confirm-new').onclick=()=>{try{localStorage.removeItem(SAVE_KEY);}catch{}location.reload();};$('cancel-new').onclick=closeModal;};
  function start(){playing=true;show('title-screen',false);show('hud');resetPosition();audio.start();if(!state.metKeeper)toast('Welcome, Wayfarer. The keeper waits beside the campfire.');else toast('Your journey continues.');save();}
  function save(){if(!playing)return;state.x=player.position.x;state.z=player.position.z;try{localStorage.setItem(SAVE_KEY,JSON.stringify(state));}catch{if(storageAvailable){storageAvailable=false;toast('Saving is unavailable. This journey will last for this session.');}}}
  function toast(message){$('toast').textContent=message;$('toast').classList.add('show');clearTimeout(toastTimeout);toastTimeout=setTimeout(()=>$('toast').classList.remove('show'),4200);}
  function discover(name,id){activeRegion=name;$('region').textContent=name.toUpperCase();if(state.discovered.includes(id))return;state.discovered.push(id);const banner=$('location-banner');banner.querySelector('h2').textContent=name;show('location-banner',false);void banner.offsetWidth;show('location-banner');clearTimeout(discoveryTimeout);discoveryTimeout=setTimeout(()=>show('location-banner',false),4500);audio.chime();}
  function updateHUD(){const max=maxHealth(state),level=levelOf(state);$('health-fill').style.width=`${state.hp/max*100}%`;$('stamina-fill').style.width=`${stamina}%`;$('health-text').textContent=`${Math.ceil(state.hp)} / ${max}`;$('shards').textContent=`◇ ${state.shards}`;$('level-badge').textContent=level;$('level-text').textContent=`LV. ${level}`;$('potion-count').textContent=state.potions;$('quest-count').innerHTML=`<span>◇</span> ${state.beacons.length} / 3 BEACONS AWAKENED`;
    $('quest-title').textContent=state.won?'The sky remembers':state.beacons.length===3?'The last guardian':state.metKeeper?'Embers of a lost world':'A light in the silence';
    $('quest-description').textContent=state.won?'The island is awake. Its untold stories are yours to find.':state.defeated.includes('warden')?'Return to the keeper at the camp.':state.beacons.length===3?'Face the Hollow Warden at the ancient gate.':state.metKeeper?'Defeat the guardians. Rekindle the three beacons in any order.':'Speak with the keeper beside the campfire.';
  }
  function openModal(kind,html){modalOpen=true;modalKind=kind;keys.clear();touchMove.x=0;touchMove.y=0;lastFocus=document.activeElement;$('modal-content').innerHTML=html;show('modal-backdrop');$('modal').focus();show('close-modal',kind!=='death');}
  function closeModal(){if(modalKind==='death')return;modalOpen=false;modalKind='';show('modal-backdrop',false);keys.clear();lastFocus?.focus?.();last=performance.now();}
  $('close-modal').onclick=closeModal;$('modal-backdrop').onclick=e=>{if(e.target===$('modal-backdrop'))closeModal();};
  function keeper(){state.metKeeper=true;updateHUD();save();if(state.defeated.includes('warden')&&!state.won){state.won=true;save();applyWorldState();victory();return;}
    const text=state.won?'The wind has a voice again. You gave this place a tomorrow, Wayfarer. Stay awhile. There are still quiet corners the sky has kept for you.':state.beacons.length===3?'Three lights, one last shadow. The Hollow Warden waits at the great ring. Watch for the red circle beneath its feet, then dodge before the blow lands.':state.beacons.length?'I felt it. The island is breathing again. Rest here, and let me strengthen your blade for the road ahead.':'Once, three beacons held these islands together. Their guardians have forgotten us. Free them, then touch each beacon to return its light. You can follow any path. The sky will wait.';
    openModal('keeper',`<div class="dialog-speaker"><div class="dialog-avatar">✧</div><div><small>KEEPER OF THE FIRST LIGHT</small><h2 id="modal-title">Elowen</h2></div></div><p>“${text}”</p><div class="modal-eyebrow" style="margin-top:25px">YOUR AETHER SHARDS &nbsp; ◇ ${state.shards}</div><button class="secondary" id="upgrade-sword" ${state.sword>=3||state.shards<upgradeCost(state.sword)?'disabled':''}>Temper blade · ${state.sword}/3 <span>${state.sword>=3?'MASTERED':`◇ ${upgradeCost(state.sword)} · +10 damage`}</span></button><button class="secondary" id="upgrade-vitality" ${state.vitality>=3||state.shards<upgradeCost(state.vitality)?'disabled':''}>Strengthen spirit · ${state.vitality}/3 <span>${state.vitality>=3?'MASTERED':`◇ ${upgradeCost(state.vitality)} · +25 health`}</span></button><button class="primary" id="rest-camp">Rest & refill flasks <b>✧</b></button><button class="secondary" id="leave-camp">The road is calling <span>↗</span></button>`);
    for(const type of ['sword','vitality'])$(`upgrade-${type}`).onclick=()=>{if(buyUpgrade(state,type)){audio.chime();save();updateHUD();keeper();}};
    $('rest-camp').onclick=()=>{state.hp=maxHealth(state);state.potions=3;closeModal();updateHUD();save();audio.chime();toast('A moment of peace. Health and flasks restored.');};$('leave-camp').onclick=closeModal;
  }
  function victory(){audio.chime();updateHUD();openModal('victory',`<div class="modal-eyebrow">CHAPTER I · COMPLETE</div><h2 id="modal-title">The sky remembers.</h2><p>The last shadow falls silent. Across the horizon, three lights answer one another — and for the first time in an age, the islands begin to sing.</p><div class="stats-grid"><div><strong>3 / 3</strong><small>BEACONS AWAKENED</small></div><div><strong>${state.totalShards}</strong><small>SHARDS FOUND</small></div><div><strong>${Math.max(1,Math.round(state.playTime/60))}m</strong><small>YOUR JOURNEY</small></div></div><p>Thank you for finding the light, Wayfarer.</p><button id="keep-exploring" class="primary">Keep exploring <b>↗</b></button>`);$('keep-exploring').onclick=closeModal;}
  function journal(){openModal('journal',`<div class="modal-eyebrow">THE WAYFARER'S JOURNAL</div><h2 id="modal-title">Embers of a lost world</h2><p>Rekindle the beacons. Bring the sky back to life.</p>${BEACONS.map(b=>`<div class="journal-row"><b>${state.beacons.includes(b.id)?'✧':'◇'}</b><div><h3>${b.name}</h3><p>${state.beacons.includes(b.id)?'Awakened. Its light has returned.':`${enemies.filter(e=>e.beacon===b.id&&!e.dead).length} guardians remain · defeat them, then press E at the beacon.`}</p></div></div>`).join('')}<div class="stats-grid"><div><strong>${levelOf(state)}</strong><small>WAYFARER LEVEL</small></div><div><strong>${swordDamage(state)}</strong><small>SWORD DAMAGE</small></div><div><strong>${state.collected.length}/45</strong><small>WILD SHARDS</small></div></div><p class="save-note">Next level: ${120-state.xp%120} experience · Guardians and beacons grant experience. Leveling up restores health.</p><button class="secondary" id="journal-map">Open the island map <span>M</span></button>`);$('journal-map').onclick=openMap;}
  function pause(){if(!playing)return;openModal('pause',`<div class="modal-eyebrow">A MOMENT BETWEEN ADVENTURES</div><h2 id="modal-title">Take a breath.</h2><p>Your journey is safe here.</p><div class="controls-grid"><span><kbd>W A S D</kbd> Move</span><span><kbd>DRAG</kbd> Look around</span><span><kbd>J / CLICK</kbd> Sword strike</span><span><kbd>SPACE</kbd> Dodge</span><span><kbd>SHIFT</kbd> Sprint</span><span><kbd>F</kbd> Jump</span><span><kbd>E</kbd> Interact</span><span><kbd>Q</kbd> Healing flask</span><span><kbd>M</kbd> Map</span><span><kbd>TAB</kbd> Journal</span></div><label class="setting-row">Visual quality<select id="quality-select"><option value="high" ${quality==='high'?'selected':''}>High</option><option value="low" ${quality==='low'?'selected':''}>Performance</option></select></label><button class="primary" id="resume">Return to the world <b>↗</b></button><button class="secondary" id="return-camp">Return to camp <span>Keep all progress</span></button><button class="secondary" id="title-return">Save & return to title <span>↗</span></button><p class="save-note">${storageAvailable?'Progress saves automatically on this browser.':'Browser storage is unavailable. Progress will not survive reloading.'}</p>`);
    $('quality-select').onchange=e=>{quality=e.target.value;renderer.setPixelRatio(quality==='low'?1:Math.min(devicePixelRatio,1.65));renderer.shadowMap.enabled=quality==='high';};$('resume').onclick=closeModal;$('return-camp').onclick=()=>{state.x=0;state.z=44;state.hp=maxHealth(state);state.potions=3;resetPosition();enemies.forEach(resetEnemy);closeModal();save();updateHUD();toast('The keeper welcomes you home.');};$('title-return').onclick=()=>{save();closeModal();playing=false;show('hud',false);show('title-screen');$('start').querySelector('span').textContent='Continue your journey';show('new-game');};
  }
  function openMap(){openModal('map',`<div class="modal-eyebrow">AN ATLAS OF FORGOTTEN PLACES</div><h2 id="modal-title">The Shattered Isles</h2><canvas id="large-map" width="700" height="700" aria-label="Island map showing your position, camp, and beacons"></canvas><div class="map-legend"><span>▲ You</span><span>⌂ Camp</span><span>◇ Beacon</span><span>✧ Gate</span></div><p class="save-note">Select a point to mark your destination. The marker appears on your compass and minimap.</p>`);drawMap($('large-map'),true);$('large-map').onclick=e=>{const r=e.target.getBoundingClientRect();waypoint={x:((e.clientX-r.left)/r.width-.5)*244,z:((e.clientY-r.top)/r.height-.5)*244};if(Math.hypot(waypoint.x,waypoint.z)>109)waypoint=null;drawMap($('large-map'),true);};}
  $('pause-button').onclick=pause;$('map-button').onclick=openMap;$('journal-button').onclick=journal;
  $('sound-button').onclick=()=>{audio.muted=!audio.muted;audio.apply();$('sound-button').textContent=audio.muted?'♩':'♪';$('sound-button').setAttribute('aria-label',audio.muted?'Enable sound':'Mute sound');toast(audio.muted?'Sound muted':'Sound on');};
  function resetEnemy(e){if(e.dead)return;e.x=e.homeX;e.z=e.homeZ;e.hp=e.maxHp;e.windup=0;e.cooldown=1;e.telegraph.visible=false;e.object.position.set(e.x,surfaceAt(e.x,e.z),e.z);}
  function die(){state.hp=0;updateHUD();audio.note(90,.5,.1);openModal('death',`<div class="modal-eyebrow">EVEN STARS NEED REST</div><h2 id="modal-title">The light carries you.</h2><p>The keeper's fire still burns. Return to camp with your discoveries, shards, and awakened beacons intact.</p><button class="primary" id="revive">Wake at the campfire <b>✧</b></button>`);$('revive').onclick=()=>{respawn(state);resetPosition();enemies.forEach(resetEnemy);invincible=3;modalKind='';closeModal();save();updateHUD();};}
  function hurt(amount){if(invincible>0||dodgeTimer>0||state.hp<=0)return;state.hp=Math.max(0,state.hp-amount);invincible=.9;shake=.22;audio.note(100,.16,.1);$('damage-flash').style.opacity='.6';setTimeout(()=>$('damage-flash').style.opacity='0',200);updateHUD();if(state.hp<=0)die();}
  function burst(position,color,count=18){for(let i=0;i<count;i++){const mesh=new THREE.Mesh(new THREE.OctahedronGeometry(.07+Math.random()*.08),new THREE.MeshBasicMaterial({color,transparent:true}));mesh.position.copy(position);scene.add(mesh);particles.push({mesh,life:.65+Math.random()*.5,max:1.1,velocity:new THREE.Vector3((Math.random()-.5)*7,2+Math.random()*5,(Math.random()-.5)*7)});}}
  function floater(text,position,color='#f4deb1'){const el=document.createElement('div');el.textContent=text;Object.assign(el.style,{position:'fixed',pointerEvents:'none',fontFamily:'Georgia,serif',fontSize:'23px',color,textShadow:'0 2px 8px #183127',zIndex:5});$('game').appendChild(el);floaters.push({el,position:position.clone(),life:1});}
  function attack(){if(!playing||modalOpen||attackCooldown>0||dodgeTimer>0)return;attackTimer=.36;attackCooldown=.48;audio.note(210,.07,.035,'triangle');
    const targets=enemies.filter(e=>!e.dead&&Math.hypot(e.x-player.position.x,e.z-player.position.z)<3.9+e.scale*.35);targets.sort((a,b)=>Math.hypot(a.x-player.position.x,a.z-player.position.z)-Math.hypot(b.x-player.position.x,b.z-player.position.z));
    if(targets.length)player.rotation.y=Math.atan2(targets[0].x-player.position.x,targets[0].z-player.position.z);
    for(const e of targets){const angle=Math.atan2(e.x-player.position.x,e.z-player.position.z);if(Math.cos(angle-player.rotation.y)<-.1)continue;e.hp-=swordDamage(state);burst(e.object.position.clone().add(new THREE.Vector3(0,1.7,0)),0xffd28d,9);floater(String(swordDamage(state)),e.object.position.clone().add(new THREE.Vector3(0,2.8*e.scale,0)));shake=.06;audio.note(340,.12,.05,'triangle');e.x+=Math.sin(angle)*.5;e.z+=Math.cos(angle)*.5;
      if(e.hp<=0){e.dead=true;e.object.visible=false;e.telegraph.visible=false;state.defeated.push(e.id);const leveled=reward(state,e.tier===3?160:e.tier===2?60:30,e.tier===3?40:e.tier===2?10:3);burst(e.object.position.clone().add(new THREE.Vector3(0,1.4,0)),0xa4edcc,22);if(e.id==='warden'){toast('The Hollow Warden is at peace. Return to Elowen.');audio.chime();}else if(leveled){toast(`Level ${levelOf(state)} · Your spirit grows stronger.`);audio.chime();}else toast(`Guardian released · +${e.tier===2?60:30} XP · +${e.tier===2?10:3} shards`);save();}
    }updateHUD();
  }
  function dodge(){if(!playing||modalOpen||dodgeCooldown>0||stamina<25)return;stamina-=25;dodgeTimer=.36;dodgeCooldown=.65;invincible=.46;dodgeVector.copy(moveVector.lengthSq()>.01?moveVector:new THREE.Vector3(Math.sin(player.rotation.y),0,Math.cos(player.rotation.y))).normalize();audio.note(130,.12,.025,'triangle');}
  function heal(){if(!playing||modalOpen)return;if(usePotion(state)){burst(player.position.clone().add(new THREE.Vector3(0,1,0)),0xaffecc,22);audio.chime();toast('The light mends you. +65 health');updateHUD();save();}else toast(state.hp>=maxHealth(state)?'Your spirit is already whole.':'Your flasks are empty. Rest at camp or awaken a beacon.');}
  function interact(){if(!playing||modalOpen)return;if(!nearby){toast('Move closer to the keeper or a beacon to interact.');return;}if(nearby.type==='keeper'){keeper();return;}if(nearby.type==='beacon'){const b=nearby.beacon;if(state.beacons.includes(b.id)){toast('This beacon already sings with light.');return;}const guardians=enemies.some(e=>e.beacon===b.id&&!e.dead);if(guardians){toast('The beacon is bound. Release its three guardians first.');return;}if(restoreBeacon(state,b.id,false)){applyWorldState();burst(b.group.position.clone().add(new THREE.Vector3(0,5,0)),b.color,65);audio.chime();updateHUD();save();toast(state.beacons.length===3?'All three beacons sing. The Hollow Warden has awakened.':`${b.name} awakened · +15 shards · Flasks refilled`);}}}
  $('attack-button').onclick=attack;$('dodge-button').onclick=dodge;$('heal-button').onclick=heal;$('touch-interact').onclick=interact;
  const touchMove={x:0,y:0};
  addEventListener('keydown',e=>{
    if(modalOpen){if(e.code==='Escape'){e.preventDefault();closeModal();return;}if(e.code==='Tab'){const list=[...$('modal').querySelectorAll('button:not(:disabled),select,[tabindex="0"]')].filter(el=>!el.classList.contains('hidden'));if(!list.length)return;const current=list.indexOf(document.activeElement),next=e.shiftKey?(current<=0?list.length-1:current-1):(current+1)%list.length;e.preventDefault();list[next].focus();}return;}
    if(['Space','Tab','KeyM','ArrowUp','ArrowDown','ArrowLeft','ArrowRight'].includes(e.code))e.preventDefault();if(!playing)return;keys.add(e.code);if(e.repeat)return;
    if(e.code==='Escape')pause();if(e.code==='Tab')journal();if(e.code==='KeyM')openMap();if(e.code==='KeyE')interact();if(e.code==='KeyQ')heal();if(e.code==='KeyJ')attack();if(e.code==='Space')dodge();if(e.code==='KeyF'&&jumpY===0){vertical=7.2;audio.note(260,.05,.02);}
  });addEventListener('keyup',e=>keys.delete(e.code));
  function clearInput(){keys.clear();drag=null;touchMove.x=0;touchMove.y=0;$('joystick').firstElementChild.style.transform='';}
  addEventListener('blur',()=>{clearInput();save();if(playing&&!modalOpen)pause();});document.addEventListener('visibilitychange',()=>{clearInput();if(document.hidden){save();if(playing&&!modalOpen)pause();}last=performance.now();});addEventListener('pagehide',save);
  $('world').addEventListener('contextmenu',e=>e.preventDefault());
  $('world').addEventListener('pointerdown',e=>{if(!playing||modalOpen)return;drag={x:e.clientX,y:e.clientY,distance:0,button:e.button};$('world').setPointerCapture(e.pointerId);});
  $('world').addEventListener('pointermove',e=>{if(!drag)return;const dx=e.clientX-drag.x,dy=e.clientY-drag.y;drag.distance+=Math.abs(dx)+Math.abs(dy);yaw-=dx*.005;pitch=THREE.MathUtils.clamp(pitch+dy*.003,.18,1.15);drag.x=e.clientX;drag.y=e.clientY;});
  $('world').addEventListener('pointerup',e=>{if(drag?.distance<7&&drag.button===0)attack();drag=null;});$('world').addEventListener('pointercancel',()=>drag=null);
  $('world').addEventListener('wheel',e=>{if(!playing)return;e.preventDefault();zoom=THREE.MathUtils.clamp(zoom+e.deltaY*.01,6,23);},{passive:false});
  const stick=$('joystick');function stickMove(e){const r=stick.getBoundingClientRect();let x=(e.clientX-r.left-r.width/2)/35,y=(e.clientY-r.top-r.height/2)/35;const len=Math.hypot(x,y);if(len>1){x/=len;y/=len;}touchMove.x=x;touchMove.y=y;stick.firstElementChild.style.transform=`translate(${x*29}px,${y*29}px)`;}
  stick.onpointerdown=e=>{stick.setPointerCapture(e.pointerId);stickMove(e);};stick.onpointermove=e=>{if(stick.hasPointerCapture(e.pointerId))stickMove(e);};stick.onpointerup=stick.onpointercancel=()=>{touchMove.x=0;touchMove.y=0;stick.firstElementChild.style.transform='';};
  function movePlayer(dt){let x=(keys.has('KeyD')||keys.has('ArrowRight')?1:0)-(keys.has('KeyA')||keys.has('ArrowLeft')?1:0)+touchMove.x,z=(keys.has('KeyS')||keys.has('ArrowDown')?1:0)-(keys.has('KeyW')||keys.has('ArrowUp')?1:0)+touchMove.y;const l=Math.hypot(x,z);if(l>1){x/=l;z/=l;}moveVector.set(x*Math.cos(yaw)+z*Math.sin(yaw),0,z*Math.cos(yaw)-x*Math.sin(yaw));const moving=l>.05,sprinting=(keys.has('ShiftLeft')||keys.has('ShiftRight'))&&stamina>2&&moving;let speed=sprinting?12:7;
    if(sprinting)stamina=Math.max(0,stamina-dt*14);else stamina=Math.min(100,stamina+dt*19);
    const d=dodgeTimer>0?dodgeVector:moveVector;if(dodgeTimer>0)speed=21;
    let nx=player.position.x+d.x*speed*dt,nz=player.position.z+d.z*speed*dt;
    for(const c of world.colliders){const dx=nx-c.x,dz=nz-c.z,dist=Math.hypot(dx,dz),r=c.r+.42;if(dist<r&&dist>.001){nx=c.x+dx/dist*r;nz=c.z+dz/dist*r;}}
    if(Math.hypot(nx,nz)>WORLD_BOUNDARY){const a=Math.atan2(nx,nz);nx=Math.sin(a)*WORLD_BOUNDARY;nz=Math.cos(a)*WORLD_BOUNDARY;if(time-saveTime>1)toast('The wind turns you back from the edge.');}
    player.position.x=nx;player.position.z=nz;
    vertical-=dt*21;jumpY=Math.max(0,jumpY+vertical*dt);if(jumpY===0)vertical=0;
    player.position.y=THREE.MathUtils.lerp(player.position.y,surfaceAt(nx,nz)+jumpY,1-Math.exp(-dt*25));
    if(moving&&attackTimer<=0){const target=Math.atan2(moveVector.x,moveVector.z);player.rotation.y+=Math.atan2(Math.sin(target-player.rotation.y),Math.cos(target-player.rotation.y))*Math.min(1,dt*15);}movePhase+=dt*(sprinting?15:11)*(moving?1:0);
    const data=player.userData;for(let i=0;i<2;i++){data.legs[i].rotation.x=moving?Math.sin(movePhase+i*Math.PI)*.65:0;data.arms[i].rotation.x=moving?Math.sin(movePhase+i*Math.PI)*.5:0;data.arms[i].rotation.z=0;}
    if(attackTimer>0){data.arms[1].rotation.x=-.9;data.arms[1].rotation.y=Math.sin((.36-attackTimer)/.36*Math.PI)*2.3-1.1;trail.position.set(nx,player.position.y+1.05,nz);trail.rotation.z=-player.rotation.y+attackTimer*9;trail.material.opacity=Math.sin(attackTimer/.36*Math.PI)*.65;}else{data.arms[1].rotation.y=0;trail.material.opacity=0;}
    data.cape.rotation.x=(moving?.18:0)+Math.sin(time*2)*.045;player.rotation.z=dodgeTimer>0?Math.sin(dodgeTimer/.36*Math.PI)*.65:0;
    if(Math.hypot(nx-37,nz-24)<18&&heightAt(nx,nz)<1.7&&moving&&Math.random()<.08)burst(new THREE.Vector3(nx,1.8,nz),0xbdeadc,2);
    if(!Number.isFinite(nx+nz)){respawn(state);resetPosition();}
  }
  function updateEnemies(dt){let closest=null,closestDist=Infinity;
    for(const e of enemies){if(e.dead)continue;const dx=player.position.x-e.x,dz=player.position.z-e.z,d=Math.hypot(dx,dz),home=Math.hypot(e.x-e.homeX,e.z-e.homeZ);if(d<closestDist&&d<17){closest=e;closestDist=d;}
      e.cooldown-=dt;
      if(e.windup>0){e.windup-=dt;e.telegraph.position.set(e.x,surfaceAt(e.x,e.z)+.1,e.z);e.telegraph.material.opacity=.13+(1-e.windup/(e.tier===3?1.05:.8))*.5;e.arms.forEach(a=>a.rotation.x=-1.8);if(e.windup<=0){e.telegraph.visible=false;e.cooldown=e.tier===3?1.3:1.65;if(d<e.attackRadius)hurt(e.tier===3?32:e.tier===2?21:14);burst(e.object.position.clone().add(new THREE.Vector3(0,.4,0)),0xd5af7c,8);}}
      else if(d<20&&home<28&&Math.hypot(player.position.x,player.position.z-42)>17){if(d<2.6*e.scale&&e.cooldown<=0){e.windup=e.tier===3?1.05:.8;e.telegraph.visible=true;}else if(d>2*e.scale){const speed=e.tier===3?3.2:3.4;e.x+=dx/d*dt*speed;e.z+=dz/d*dt*speed;}e.object.rotation.y=Math.atan2(dx,dz);e.arms.forEach((a,i)=>a.rotation.x=Math.sin(time*6+i*Math.PI)*.3);}
      else if(home>1){e.x+=(e.homeX-e.x)/home*dt*2.3;e.z+=(e.homeZ-e.z)/home*dt*2.3;}
      e.object.position.set(e.x,surfaceAt(e.x,e.z)+Math.sin(time*3+e.homeX)*.025,e.z);
    }
    show('enemy-status',!!closest);if(closest){$('enemy-status').querySelector('span').textContent=closest.tier===3?'THE HOLLOW WARDEN':closest.tier===2?'BEACON GUARDIAN':'HOLLOW SENTINEL';$('enemy-status').querySelector('.bar>div').style.width=`${Math.max(0,closest.hp/closest.maxHp*100)}%`;}
  }
  function checkWorld(){nearby=null;const p=player.position;let best=6;
    const npcDistance=Math.hypot(p.x-world.npc.position.x,p.z-world.npc.position.z);if(npcDistance<best){nearby={type:'keeper'};best=npcDistance;}
    for(const b of world.beaconObjects){const d=Math.hypot(p.x-b.x,p.z-b.z);if(d<best){nearby={type:'beacon',beacon:b};best=d;}}
    show('interact',!!nearby);if(nearby)$('interact').querySelector('span').textContent=nearby.type==='keeper'?'Speak with Elowen':state.beacons.includes(nearby.beacon.id)?'The beacon is awakened':'Awaken the beacon';
    for(const shard of world.pickups)if(shard.object.visible&&Math.hypot(p.x-shard.x,p.z-shard.z)<1.6){if(collectShard(state,shard.id)){shard.object.visible=false;audio.note(620+Math.random()*300,.2,.025,'sine');burst(shard.object.position,0xc4ffe0,5);updateHUD();save();}}
    let region='The Sunlit Reach',id='reach';for(const b of BEACONS)if(Math.hypot(p.x-b.x,p.z-b.z)<28){region=b.name;id=b.id;}if(Math.hypot(p.x,p.z+18)<20){region='The Aether Gate';id='gate';}if(region!==activeRegion)discover(region,id);
    const angle=((-yaw*180/Math.PI)%360+360)%360;const dirs=['N','NE','E','SE','S','SW','W','NW'];const heading=dirs[Math.round(angle/45)%8];$('compass-strip').innerHTML=`<span>· · ·</span> ${heading} <span>· · ·</span>`;
    if(waypoint){const distance=Math.round(Math.hypot(p.x-waypoint.x,p.z-waypoint.z));$('waypoint-bearing').textContent=`◇ ${distance}m`;const bearing=Math.atan2(waypoint.x-p.x,p.z-waypoint.z)+yaw;const offset=Math.atan2(Math.sin(bearing),Math.cos(bearing));$('waypoint-bearing').style.transform=`translateX(${THREE.MathUtils.clamp(offset,-1.6,1.6)*55-20}px)`;show('waypoint-bearing');$('ambient-label').innerHTML=`Your marked destination · ${distance}m<small>Open the map to choose another path.</small>`;}else {show('waypoint-bearing',false);$('ambient-label').innerHTML=`${state.beacons.length?'The island stirs. Keep following the light.':'A quiet wind. An unfamiliar sky.'}<small>${storageAvailable?'Your journey is saved automatically.':'Session only · saving unavailable'}</small>`;}
  }
  function drawMap(canvas,large=false){const ctx=canvas.getContext('2d'),w=canvas.width,scale=w/244;ctx.clearRect(0,0,w,w);ctx.fillStyle='#223f3a';ctx.fillRect(0,0,w,w);ctx.save();ctx.translate(w/2,w/2);ctx.scale(scale,scale);
    const g=ctx.createRadialGradient(-25,-40,10,0,0,116);g.addColorStop(0,'#65755b');g.addColorStop(.65,'#425f4e');g.addColorStop(1,'#74917a');ctx.fillStyle=g;ctx.beginPath();for(let i=0;i<=100;i++){const a=i/100*Math.PI*2,r=110+Math.sin(a*9)*2+Math.cos(a*13)*2;ctx.lineTo(Math.sin(a)*r,Math.cos(a)*r);}ctx.closePath();ctx.fill();ctx.strokeStyle='#a3b59266';ctx.lineWidth=.6;ctx.stroke();
    ctx.strokeStyle='#c5c09355';ctx.lineWidth=2;for(const points of [[[0,70],[0,20],[0,-18],[0,-78]],[[0,20],[-27,9],[-57,-13]],[[0,5],[25,-13],[51,-38]]]){ctx.beginPath();points.forEach(([x,z])=>ctx.lineTo(x,z));ctx.stroke();}
    ctx.fillStyle='#679c91';ctx.beginPath();ctx.ellipse(37,24,22,16,0,0,7);ctx.fill();
    ctx.strokeStyle='#b8c6a51a';ctx.lineWidth=.5;for(let r=30;r<110;r+=20){ctx.beginPath();ctx.arc(0,0,r,0,7);ctx.stroke();}
    const fontSize=large?5:8;ctx.textAlign='center';ctx.textBaseline='middle';
    function marker(x,z,text,color){ctx.font=`${large?9:12}px Georgia`;ctx.fillStyle=color;ctx.fillText(text,x,z);}
    marker(CAMP.x,CAMP.z,'⌂','#e6d197');marker(0,-18,'✧',state.won?'#b7efc0':'#e5d4ae');
    for(const b of BEACONS){marker(b.x,b.z,state.beacons.includes(b.id)?'✦':'◇',state.beacons.includes(b.id)?'#b5f6cf':'#f0d291');if(large){ctx.font=`${fontSize}px Georgia`;ctx.fillStyle='#e4e4ce';ctx.fillText(b.name,b.x,b.z+10);}}
    if(large){ctx.font='5px Georgia';ctx.fillStyle='#dddbc0';ctx.fillText("Keeper's camp",CAMP.x,CAMP.z+9);ctx.fillText('The Aether Gate',0,-8);ctx.fillStyle='#b5d4bf';ctx.font='italic 5px Georgia';ctx.fillText('The Stillwater',39,27);}
    if(waypoint){ctx.strokeStyle='#f5e6a4';ctx.lineWidth=.6;ctx.beginPath();ctx.arc(waypoint.x,waypoint.z,4,0,7);ctx.moveTo(waypoint.x-6,waypoint.z);ctx.lineTo(waypoint.x+6,waypoint.z);ctx.moveTo(waypoint.x,waypoint.z-6);ctx.lineTo(waypoint.x,waypoint.z+6);ctx.stroke();}
    ctx.save();ctx.translate(player.position.x,player.position.z);ctx.rotate(-player.rotation.y);ctx.fillStyle='#f6f0d1';ctx.shadowColor='#152c25';ctx.shadowBlur=4;ctx.beginPath();ctx.moveTo(0,large?3.8:5);ctx.lineTo(-2.8,-3);ctx.lineTo(0,-1.4);ctx.lineTo(2.8,-3);ctx.closePath();ctx.fill();ctx.restore();ctx.restore();
  }
  function updateCamera(dt){if(!playing){camera.position.set(42+Math.sin(time*.035)*2,26,60);camera.lookAt(-3,9,-14);return;}cameraTarget.set(player.position.x,player.position.y+2.1,player.position.z);
    let distance=zoom;const sx=Math.sin(yaw),sz=Math.cos(yaw);for(const c of world.colliders){const dx=c.x-player.position.x,dz=c.z-player.position.z,along=dx*sx+dz*sz,across=Math.abs(dx*sz-dz*sx);if(along>2&&along<distance&&across<c.r+.55)distance=Math.max(3.8,along-c.r-.6);}
    cameraPosition.set(cameraTarget.x+sx*distance*Math.cos(pitch),cameraTarget.y+distance*Math.sin(pitch),cameraTarget.z+sz*distance*Math.cos(pitch));cameraPosition.y=Math.max(cameraPosition.y,surfaceAt(cameraPosition.x,cameraPosition.z)+1.3);camera.position.lerp(cameraPosition,1-Math.exp(-dt*7));if(shake>0){camera.position.x+=(Math.random()-.5)*shake;camera.position.y+=(Math.random()-.5)*shake;shake=Math.max(0,shake-dt);}camera.lookAt(cameraTarget);
  }
  function frame(now){requestAnimationFrame(frame);const dt=Math.min((now-last)/1000,.045);last=now;time+=dt;
    if(!modalOpen)world.update(time,dt);
    if(playing&&!modalOpen){state.playTime+=dt;attackTimer=Math.max(0,attackTimer-dt);attackCooldown=Math.max(0,attackCooldown-dt);dodgeTimer=Math.max(0,dodgeTimer-dt);dodgeCooldown=Math.max(0,dodgeCooldown-dt);invincible=Math.max(0,invincible-dt);movePlayer(dt);updateEnemies(dt);checkWorld();$('stamina-fill').style.width=`${stamina}%`;if(time-saveTime>5){saveTime=time;save();}if(time-mapTime>.12){mapTime=time;drawMap($('minimap'));}}
    for(let i=particles.length-1;i>=0;i--){const p=particles[i];p.life-=dt;p.velocity.y-=dt*8;p.mesh.position.addScaledVector(p.velocity,dt);p.mesh.material.opacity=Math.max(0,p.life/p.max);if(p.life<=0){scene.remove(p.mesh);p.mesh.geometry.dispose();p.mesh.material.dispose();particles.splice(i,1);}}
    for(let i=floaters.length-1;i>=0;i--){const f=floaters[i];f.life-=dt;f.position.y+=dt;const v=f.position.clone().project(camera);f.el.style.left=`${(v.x*.5+.5)*innerWidth}px`;f.el.style.top=`${(-v.y*.5+.5)*innerHeight}px`;f.el.style.opacity=Math.max(0,f.life);if(f.life<=0){f.el.remove();floaters.splice(i,1);}}
    if(!modalOpen)updateCamera(dt);post.render(scene,camera,time,quality==='high');
  }
  addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight);});
  $('world').addEventListener('webglcontextlost',e=>{e.preventDefault();save();show('error-screen');$('error-message').textContent='The graphics connection was interrupted. Your last autosave is safe. Reload to continue.';});
  // Optional browser-native tools expose the same player-facing journal and map.
  if(navigator.modelContext?.registerTool){
    navigator.modelContext.registerTool({name:'aetherfall_journey_status',description:'Read the current Aetherfall quest, health, upgrades, and controls.',inputSchema:{type:'object',properties:{},additionalProperties:false},execute:async()=>({content:[{type:'text',text:JSON.stringify({level:levelOf(state),health:state.hp,maxHealth:maxHealth(state),shards:state.shards,beacons:state.beacons,quest:$('quest-description').textContent,controls:'WASD move, drag camera, J attack, Space dodge, E interact, Q heal, F jump, M map, Tab journal'})}]})});
    navigator.modelContext.registerTool({name:'aetherfall_open_journal',description:'Pause Aetherfall and open the player journal.',inputSchema:{type:'object',properties:{},additionalProperties:false},execute:async()=>{if(playing)journal();return {content:[{type:'text',text:playing?'Journal opened.':'Begin your journey first.'}]};}});
  }
  requestAnimationFrame(frame);
}
class Soundscape{
  constructor(){this.ctx=null;this.master=null;this.muted=false;this.timer=null;}
  start(){try{if(!this.ctx){this.ctx=new (window.AudioContext||window.webkitAudioContext)();this.master=this.ctx.createGain();this.master.gain.value=.22;this.master.connect(this.ctx.destination);let n=0;const tones=[146.83,196,220,293.66,392,293.66,220,196];this.timer=setInterval(()=>{if(!document.hidden&&!this.muted)this.note(tones[n++%tones.length],2.8,.045,'sine');},1900);}this.ctx.resume();}catch{}}
  apply(){if(this.master)this.master.gain.setTargetAtTime(this.muted?0:.22,this.ctx.currentTime,.1);}
  note(freq,duration,volume=.06,type='sine'){if(!this.ctx||this.muted)return;const now=this.ctx.currentTime,o=this.ctx.createOscillator(),g=this.ctx.createGain();o.type=type;o.frequency.setValueAtTime(freq,now);g.gain.setValueAtTime(0,now);g.gain.linearRampToValueAtTime(volume,now+.015);g.gain.exponentialRampToValueAtTime(.0001,now+duration);o.connect(g);g.connect(this.master);o.start();o.stop(now+duration+.02);o.onended=()=>{o.disconnect();g.disconnect();};}
  chime(){[523.25,659.25,783.99].forEach((f,i)=>setTimeout(()=>this.note(f,.8,.09),i*110));}
}

try{init();}catch(error){console.error(error);show('error-screen');$('error-message').textContent='Your browser could not start the 3D world. Enable hardware acceleration, then reload, or try a recent version of Chrome, Edge, Firefox, or Safari.';}
